using System.Collections.ObjectModel;

namespace YDKE_Windows;

internal sealed record HelpSection(string Id, string Title, string Body);

internal sealed record HelpDocument(string Title, string Intro, IReadOnlyList<HelpSection> Sections)
{
    public string ReadableText => string.Join("\n\n", new[] { Intro }.Concat(Sections.Select(section => $"{section.Title}\n{section.Body}")));
}

internal static class HelpContent
{
    private static readonly IReadOnlyDictionary<string, HelpDocument> Documents =
        new ReadOnlyDictionary<string, HelpDocument>(new Dictionary<string, HelpDocument>(StringComparer.Ordinal)
        {
            ["tr"] = Turkish(),
            ["en"] = English(),
            ["de"] = German(),
            ["fr"] = French(),
            ["es"] = Spanish(),
            ["pt"] = Portuguese(),
            ["nl"] = Dutch(),
        });

    public static HelpDocument Get(string language) => Documents.TryGetValue(language, out var document)
        ? document
        : Documents[UserSettings.DefaultUiLanguage];

    private static HelpDocument Turkish() => new(
        "YDKE yardımı",
        "YDKE, kelime öğrenmeyi kartlar, testler, kelime listeleri, istatistikler ve 25 yerel oyunla destekleyen Windows uygulamasıdır. Bu yardım sayfası uygulamanın gerçek masaüstü akışını anlatır. Metni seçip kopyalayabilir, Tab ve Shift+Tab ile kontroller arasında ilerleyebilir, kısa yardım pencerelerini Önceki sayfa ve Sonraki sayfa düğmeleriyle okuyabilirsin.",
        [
            new("start", "Başlarken: üst çubuk ve menü", "Üst çubukta Öğrenme dili ve Seviye seçicileri bulunur. Bunlar hangi kelime havuzuyla çalışacağını belirler. Uygulama dili üst çubukta değil, Ayarlar > Çalışmam bölümündeki Uygulama dili seçicisinden değiştirilir. Pencereli veya Tam ekran düğmesi görünüm modunu değiştirir; F11 aynı işi yapar, Esc tam ekrandan çıkar.\n\nSol menü Ana Sayfa, Kartlar, Test, Kelimeler, Phrasal Verbs, Basit Oyunlar, Karmaşık Oyunlar, İstatistikler, Ayarlar, Yardım ve Hakkında bölümlerini açar. Phrasal Verbs ekranı açıkken Seviye seçicisi geçici olarak devre dışı bırakılır; diğer ekranlara geçince yeniden etkinleşir. Menü kapalıyken her öğe simgesiyle görünür; klavyeyle Tab kullanıldığında erişilebilir adı okunur. Bir bölüm açıldığında uygulama önceki çalışma bağlamını korur."),
            new("accessibility", "Erişilebilirlik ve klavye kullanımı", "Kontrollerin metin etiketleri renk veya simgeye tek başına bağlı değildir. Düğmeler en az 48 piksel hedef alanı, görünür odak çerçevesi ve yüksek karşıtlık desteği kullanır. Metin boyutu Ayarlar > Renkler ve yazılar bölümünde artırılabilir; uygulama küçük ayarlarda bile okunabilir bir yazı tabanını korur.\n\nTab bir sonraki kontrole, Shift+Tab önceki kontrole gider. Enter seçili düğmeyi çalıştırır. Kartlarda Boşluk anlamı gösterir; 1–4 değerlendirmeyi seçer; sol ve sağ oklar kartlar arasında ilerler; U kelimeyi biliniyor olarak işaretler. Testte 1–4 seçenekleri seçer ve Enter yanıt kaydedildikten sonra Devam düğmesini çalıştırır. Oyunlarda düğmelerin adları, durumları ve yardım metinleri ekran okuyuculara aktarılır. Renkli doğru/yanlış göstergeleri her zaman metin veya simgeyle birlikte verilir."),
            new("cards", "Kartlar: gör, düşün ve ilerle", "Kartlar bölümü kısa bir çalışma oturumu başlatır. Önce kelimeyi düşün, sonra Anlamı göster düğmesini seç. Anlam ve örnek cümle görünür; Dinle düğmesi kelimeyi cihazındaki hedef dil sesiyle okur. Favori ve Bu kelimeyi biliyorum düğmeleri kişisel işaretlerdir.\n\nAnlamı okuduktan sonra Sonraki düğmesini seçerek kartı tamamla ve ilerle. Önceki ve Sonraki düğmeleri kayıtlı kartlar arasında hareket eder; Geri al son tamamlanan kartı geri getirir. Kelimeyi biliniyor olarak işaretlemek için Kartlar veya Kelimeler içindeki biliniyor aracını kullanabilirsin.\n\nKart açılmadan Sonraki düğmesi etkinleşmez. Bu, anlamı görmeden ilerlemeyi önler."),
            new("quiz", "Test: kaydedilen yanıt ve geri bildirim", "Test her zaman seçili Öğrenme dili ve Seviye için numaralı test adacıkları ızgarasıyla açılır. Testini açmak için bir adacık seç. Her adacık 20 soru içerir; son adacıkta kalan soru sayısı 20'den az olabilir.\n\nHer adacık kendi sorularını ve seçeneklerini olduğu gibi, yanıtlarını ve kaldığın yeri ayrı kaydeder. Kutucuğunu açınca kayıtlı oturuma kaldığın yerden devam edersin; tamamlanan adacık sonuçlarını açar. Başka bir test adacığı seç, ilerlemeni silmeden seçiciye döner.\n\nHer soruda anlamı oku ve dört kelime arasından birini seç. Seçimin hemen kaydedilmezse uygulama sonraki soruya geçmez. Geri bildirim doğru yanıtı, senin seçimini ve gerekiyorsa açıklamayı metinle gösterir. Örnek veya karşılaştırma için Yanıta bakalım'ı aç. Devam düğmesi yalnızca yanıt kaydedildikten sonra etkinleşir; düğmeyi veya Enter'ı kullanarak sonraki soruya geçebilirsin. Sonuç ekranı ilk deneme doğruluğunu oyun puanlarından ve kart öz değerlendirmelerinden ayrı tutar.\n\nBu testi yeniden çöz, o adacığın testini tüm sorularıyla baştan başlatır."),
            new("words", "Kelimeler: ara, süz ve tek tek çalış", "Kelimeler bölümü aynı anda uzun bir listeyi sıkıştırmak yerine bir kelimeyi tam olarak gösterir. Arama kutusunda kelime, anlam veya kategori arayabilirsin. Kategori, biliniyor ve favori filtrelerini birlikte kullanabilirsin. Filtreleri temizle sonuçları başlangıç durumuna döndürür.\n\nÖnceki kelime ve Sonraki kelime düğmeleri sonuçlar arasında ilerler. Her kelime için anlam, örnek, Dinle, favori ve biliniyor araçları bulunur. Biliniyor işareti Kartlar ile ortaktır; burada işaretlediğin kelime Kartlar içinde de işaretli görünür.\n\n20 soruluk test seç düğmesi, seçili Öğrenme dili ve Seviye için numaralı test adacıkları ızgarasını açar. Arama filtreleri testleri değiştirmez. Her adacık 20 sorudur; sonuncuda daha az olabilir. Her adacık kendi sorularını ve seçeneklerini olduğu gibi, yanıtlarını ve kaldığın yeri ayrı kaydeder. Kutucuğunu açarak kayıtlı oturuma devam et veya tamamlandıysa sonuçlarını gör. Seçiciye dönmek ilerlemeyi silmez. Bu testi yeniden çöz, o adacığın testini tüm sorularıyla baştan başlatır."),
            new("games", "Oyunlar: 25 farklı çalışma biçimi", "Basit Oyunlar ve Karmaşık Oyunlar menüleri toplam 25 yerel oyunu gösterir. Oyun kataloğu tek bir pencerede açılır; oyun kartını seçip Oyna düğmesine bas. Oyun ekranındaki İpucu, Nasıl oynanır ve örnek/ampul düğmeleri sorunun ne istediğini açıklar. Bazı oyunlar süre, bazıları can veya tur kullanır; üstteki HUD puan, seri, tur ve süre/can bilgisini metin olarak gösterir.\n\nOyunlar şunlardır: Hangman, Cloze Test, Dictation, Speed Round, Survival Streak, True or False, Word Class, Memory, Odd One Out, Word Race, Sentence Scramble, Reading Comprehension, Word Morph, Bingo, Boss Rush, CodyCross, Crossword, Daily Challenge, Scrabble, Word Guess, Category Sprint, Listening Choice, Matrix, Clue Detective ve Scramble.\n\nHer oyunun kelime havuzu Öğrenme dili ve Seviye seçicilerine bağlıdır. Bazı oyunlarda hedef dil için yeterli uzunlukta veya örnekli kelime yoksa oyun içeriği sınırlı olabilir; bu bir hesap veya internet hatası değildir. Oyun bırakılırken onay istenir; kaydedilmiş öğrenme ilerlemesi korunur."),
            new("statistics", "İstatistikler: ölçümleri birbirine karıştırma", "İstatistikler üç bölüme ayrılır. Genel bakış bugün ve son yedi gündeki farklı kelimeleri, mevcut çalışma dilini ve tekrar zamanı gelen kelimeleri gösterir. Yanıtlar test ilk denemelerini, puanlanan oyun yanıtlarını ve tamamlanan oyunları ayrı gösterir. Kartlar bölümü kart öz değerlendirmelerini ve eski sayaç ayrıntılarını sunar.\n\nKart öz değerlendirmeleri doğruluk puanı değildir: Yardım et, Zor, Biliyordum ve Kolay senin kendi hatırlama değerlendirmelerindir. Her satırda renk, değerlendirme adı, açıklama ve sayı birlikte bulunur. Büyük metin ayarında satırlar sayfalara ayrılır; Önceki ve Sonraki düğmeleri sayfayı değiştirir ve ekran okuyucu mevcut sayfayı duyurur. Renkler okunamasa bile metin anlamı korur."),
            new("settings", "Ayarlar: çalışma, görünüm ve yetişkin araçları", "Çalışmam bölümünde Uygulama dili, günlük hedef, Daha az hareket ve Süre sınırı olmadan oyna seçenekleri bulunur. Günlük hedef 1 ile 10.000 arasında tam sayı olmalıdır. Değişiklikler Kaydet seçilene kadar taslaktır; geçersiz sayı kaydedilmez ve hata metni doğrudan hedef alanında gösterilir.\n\nRenkler ve yazılar bölümünde metin boyutu yüzde 85–140 arasında ayarlanır. Arka plan, düğme ve panel renklerini seçebilirsin; uygulama önizlemede yazı ve sınır karşıtlığını korur. Gelişmiş renk araçları açılır bir bölümde bulunur ve HEX değerleri doğrudan girilebilir.\n\nBüyükler için bölümünde yerel yedek dışa/içe aktarma ve tüm yerel ayarları/öğrenme hafızasını sıfırlama araçları vardır. Sıfırlama iki kez açıkça belirtilir ve onay ister; yalnızca bu cihazdaki yerel veriler etkilenir."),
            new("cloud", "Yerel yedekler ve gizlilik", "YDKE ile öğrenmek için hesap veya oturum açma gerekmez. Öğrenme içeriği ve ilerleme bu cihazda yerel olarak saklanır.\n\nAyarlar > Büyükler için bölümündeki Bir kopya oluştur, yerel yedek dosyası çıkarır. Bir kopya aç işlemi dosyayı doğrular, önce güvenlik kopyası alır, sonra onayla birlikte yerel ayar ve ilerlemeyi değiştirir.\n\nVarsayılan çalışma tamamen çevrimdışıdır. Yedek dosyalar yalnızca öğrenme verisini taşır; hesap bilgisi veya gizli kimlik verisi içermez."),
            new("audio", "Dinle düğmesi ve sorun giderme", "Dinle düğmesi kelimeyi hedef dilde Windows 11'in yerel konuşma sesleriyle okumayı dener. Dinle çalışmıyorsa şu adımları uygula: Windows Ayarlar > Zaman ve dil > Dil ve bölge > Dil ekle (gerekirse) > ilgili dili seç > Dil seçenekleri > Konuşma paketini yükle. Kurulumdan sonra YDKE'yi kapatıp yeniden aç. Uygulama ses için internetten bir servis çağırmaz.\n\nSes düğmesi etkin değilse oyun veya kelime için sesli içerik bulunmuyor olabilir. Bu durum kelimeyi yazılı olarak çalışmanı engellemez. Daha az hareket seçeneği animasyonları azaltır; ses özelliğini kapatmaz.\n\nBir dil veya seviye değişikliğinden sonra kelime havuzu yeniden yüklenebilir. Kısa bir yükleme göstergesi görünürken düğmeler geçici olarak devre dışı bırakılır; bu sırada seçimleri tekrarlamak gerekmez."),
            new("data", "İçerik, kaynaklar ve uygulama lisansı", "Kelime listeleri ve okuma içerikleri uygulamayla birlikte yerel olarak paketlenir. Bazı tanım ve örnek cümleler açık topluluk kaynaklarından gelir; ilgili atıf ve lisans bilgileri Hakkında sayfasında ve paketteki NOTICE dosyasında bulunur. YDKE'nin kendi kaynak kodu ve arayüzü PolyForm Noncommercial License 1.0.0 kapsamındadır.\n\nTicari kullanım izinsiz değildir. Kişisel kullanım, öğrenme, araştırma, hobi projeleri, okullar, üniversiteler, kamu kurumları ve kâr amacı gütmeyen kuruluşlar için lisans metnindeki koşullar geçerlidir. Tam telif sahipleri, izin adresleri ve lisans bağlantısı Hakkında sayfasının en üstündeki uygulama lisansı bölümündedir.\n\nYDKE, YDS, YÖKDİL, ÜDS, TOEFL, telc veya CEFR kurumlarının resmi ürünü değildir. Sınav ve marka adları yalnızca çalışma hedefini açıklamak için kullanılır."),
        ]);

    private static HelpDocument English() => new(
        "YDKE help",
        "YDKE is a native Windows vocabulary app with cards, quizzes, word lists, statistics and 25 local games. This help describes the actual desktop app, not the retired web interface. You can select and copy the text, move with Tab and Shift+Tab, and read short help pages with Previous page and Next page.",
        [
            new("start", "Getting started: the top bar and menu", "The top bar contains Learning language and Level selectors. They define the vocabulary pool used by Cards, Quiz, Words, Phrasal Verbs and Games. App language is changed in Settings > My practice, not in the top bar. Windowed or Full screen changes the window mode; F11 does the same and Esc leaves full screen.\n\nThe left navigation opens Home, Cards, Quiz, Words, Phrasal Verbs, Simple Games, Complex Games, Statistics, Settings, Help and About. On the Phrasal Verbs page, the Level selector is intentionally disabled; it becomes available again on other pages. Every navigation item has a text name for keyboard and screen-reader users. Changing a section keeps the current study context.")
                , new("accessibility", "Accessibility and keyboard use", "Controls do not depend on colour or an icon alone. Buttons use at least 48-pixel targets, visible focus visuals and high-contrast support. Increase text size in Settings > Colors & text; the app keeps a readable text floor even at smaller settings.\n\nTab moves forward and Shift+Tab moves backward. Enter invokes the focused button. In Cards, Space reveals the meaning, 1–4 select a rating, arrow keys move between cards and U toggles known. In Quiz, 1–4 select an answer and Enter continues after the saved answer. Games expose names, states and help text to assistive technology. Correct and incorrect states always include text or symbols in addition to colour.")
                , new("cards", "Cards: reveal, read and continue", "Start a short Cards session. Think about the word, then choose Show meaning. The meaning and example appear; Listen uses a locally installed voice for the target language. Favourite and I know this word are personal marks.\n\nAfter reading the meaning, choose Next to complete the card and continue. Previous and Next move through saved cards; Undo brings back the last completed card. Use the known tool in Cards or Words when you want to mark a word as known.\n\nNext stays disabled until the meaning is revealed. This keeps the learning step clear and prevents moving on without seeing the answer.")
                , new("quiz", "Quiz: saved answers and feedback", "Quiz always opens the numbered test-island grid for the selected Learning language and Level. Choose an island to open its test. Each island contains 20 questions, except the last island, which may contain fewer.\n\nEach island saves its own exact questions, choices, answers and current position. Opening its tile resumes that saved session; a completed island opens its results. Choose another test island returns to the picker without discarding progress.\n\nRead the meaning and choose one of four words. The app does not move on until the answer has been saved. Feedback names the correct answer, your choice and any useful comparison text. Look at the answer opens an example or comparison. Continue becomes available only after the saved answer. The result records first-attempt quiz accuracy separately from game scores and Cards self-ratings.\n\nTry this test again restarts the whole test for that island from the beginning.")
                , new("words", "Words: search, filter and practise", "Words shows one complete result at a time instead of compressing a long list. Search by word, meaning or category and combine category, known and favourite filters. Clear filters returns to the starting results.\n\nPrevious word and Next word move between matches. Each result includes meaning, example, Listen, favourite and known tools. Known is shared with Cards, so a mark made in either place is visible in the other.\n\nChoose a 20-question test opens the numbered test-island grid for the selected Learning language and Level. Search filters do not change the tests. Each island has 20 questions; the last may have fewer. Each saves its own exact questions, choices, answers and position. Open its tile to resume the saved session or see completed results. Returning to the picker keeps progress. Try this test again restarts that island's whole test.")
                , new("games", "Games: 25 study mechanics", "Simple Games and Complex Games contain 25 local games. Choose a game card and Play. The game toolbar offers How to play, Hint and, where useful, a definition/example bulb. The HUD presents score, streak, round and lives or time as text as well as visual progress.\n\nThe current catalog is Hangman, Cloze Test, Dictation, Speed Round, Survival Streak, True or False, Word Class, Memory, Odd One Out, Word Race, Sentence Scramble, Reading Comprehension, Word Morph, Bingo, Boss Rush, CodyCross, Crossword, Daily Challenge, Scrabble, Word Guess, Category Sprint, Listening Choice, Matrix, Clue Detective and Scramble.\n\nGames use the selected Learning language and Level. Some mechanics need suitable word length, examples or reading content; limited availability is a dataset constraint, not an account or internet error. Leaving a game asks for confirmation and keeps saved learning progress.")
                , new("statistics", "Statistics: keep measurements separate", "Statistics has Overview, Answers and Cards sections. Overview shows unique words today and in the last seven days, the current study language and due reviews. Answers separates first-attempt Quiz results, scored Game answers and completed games. Cards shows self-ratings and retained legacy counters.\n\nCards self-ratings are not accuracy scores. Help me, Hard, I knew it and Easy describe your own recall judgement. Each row includes a label, plain-language description and count; colour is only an additional cue. Large text settings page the rows, and Previous/Next announces the current page to screen readers.")
                , new("settings", "Settings: practice, appearance and grown-up tools", "My practice contains App language, daily goal, Less movement and Play without a timer. The daily goal is a whole number from 1 to 10,000. Changes are drafts until Save; invalid input is rejected with an inline message.\n\nColors & text controls text size from 85% to 140% and lets you preview background, button and panel colours. The preview keeps readable text and boundary contrast. Advanced colour tools are presented separately and accept HEX values.\n\nFor grown-ups contains local backup export/import and a confirmation-gated reset of local settings and learning memory.")
                , new("cloud", "Local backups and privacy", "No account or sign-in is required to learn with YDKE. Learning content and progress are stored locally on this device.\n\nIn Settings > For grown-ups, Make a copy exports a local backup file. Open a copy validates the file, creates a safety copy first, and then replaces local settings and progress after confirmation.\n\nLearning is offline by default. Backup files carry only learning data and do not include account or secret credential information.")
                , new("audio", "Listen and troubleshooting", "Listen uses an installed Windows 11 speech voice for the target language. If Listen does not work, follow these steps: Windows Settings > Time & language > Language & region > Add a language (if needed) > select the language > Language options > install Speech. Restart YDKE after installation. YDKE does not call an online speech service for learning.\n\nA disabled Listen control may mean that the current word or game has no audio target. Text practice remains available. Less movement reduces animations but does not turn audio off.\n\nChanging a language or level may reload the vocabulary pool. During the short loading state, controls are disabled so the same change is not submitted twice.")
                , new("data", "Content, sources and licence", "Vocabulary and reading content is bundled locally. Some definitions and examples come from open community sources; attribution and licence details are in the About page and the NOTICE file shipped with the app. YDKE's own source code and interface are covered by the PolyForm Noncommercial License 1.0.0.\n\nCommercial use requires prior permission. The licence terms cover personal study, research, hobby projects, schools, universities, public institutions and nonprofit organisations as described in the licence. Copyright holders, permission addresses and the full licence link appear at the top of About.\n\nYDKE is not an official product of YDS, YÖKDİL, ÜDS, TOEFL, telc or CEFR organisations. Exam and brand names describe study goals only.")
        ]);

    private static HelpDocument German() => Localized("de", 
        "YDKE-Hilfe",
        "YDKE ist eine native Windows-App zum Wortschatzlernen mit Karten, Quiz, Wortlisten, Statistiken und 25 lokalen Spielen. Diese Hilfe beschreibt die Desktop-App, nicht die frühere Weboberfläche. Der Text kann ausgewählt, kopiert und mit Tab oder Shift+Tab gelesen werden; die lange Seite kann gescrollt werden.",
        "Erste Schritte", "Barrierefreiheit und Tastatur", "Karten", "Quiz", "Wörter", "Spiele", "Statistik", "Einstellungen", "Lokale Sicherungen und Datenschutz", "Anhören und Fehlerbehebung", "Inhalte, Quellen und Lizenz");

    private static HelpDocument French() => Localized("fr", 
        "Aide YDKE",
        "YDKE est une application Windows native pour apprendre le vocabulaire avec cartes, quiz, listes de mots, statistiques et 25 jeux locaux. Cette aide décrit l’application de bureau, pas l’ancienne interface web. Le texte peut être sélectionné et copié; utilisez Tab ou Maj+Tab et faites défiler cette longue page.",
        "Premiers pas", "Accessibilité et clavier", "Cartes", "Quiz", "Mots", "Jeux", "Statistiques", "Réglages", "Sauvegardes locales et confidentialité", "Écouter et dépannage", "Contenu, sources et licence");

    private static HelpDocument Spanish() => Localized("es", 
        "Ayuda de YDKE",
        "YDKE es una aplicación nativa de Windows para aprender vocabulario con tarjetas, pruebas, listas, estadísticas y 25 juegos locales. Esta ayuda describe la aplicación de escritorio, no la antigua interfaz web. El texto se puede seleccionar y copiar; usa Tab o Mayús+Tab y desplázate por esta página larga.",
        "Primeros pasos", "Accesibilidad y teclado", "Tarjetas", "Prueba", "Palabras", "Juegos", "Estadísticas", "Ajustes", "Copias locales y privacidad", "Escuchar y solucionar problemas", "Contenido, fuentes y licencia");

    private static HelpDocument Portuguese() => Localized("pt", 
        "Ajuda do YDKE",
        "O YDKE é uma aplicação nativa do Windows para aprender vocabulário com cartões, testes, listas, estatísticas e 25 jogos locais. Esta ajuda descreve a aplicação de computador, não a antiga interface web. O texto pode ser selecionado e copiado; use Tab ou Shift+Tab e percorra esta página longa.",
        "Primeiros passos", "Acessibilidade e teclado", "Cartões", "Teste", "Palavras", "Jogos", "Estatísticas", "Definições", "Cópias locais e privacidade", "Ouvir e resolução de problemas", "Conteúdo, fontes e licença");

    private static HelpDocument Dutch() => Localized("nl", 
        "YDKE-help",
        "YDKE is een native Windows-app om woordenschat te leren met kaarten, toetsen, woordenlijsten, statistieken en 25 lokale spellen. Deze hulp beschrijft de desktop-app, niet de oude webinterface. Tekst kan worden geselecteerd en gekopieerd; gebruik Tab of Shift+Tab en scroll door deze lange pagina.",
        "Aan de slag", "Toegankelijkheid en toetsenbord", "Kaarten", "Toets", "Woorden", "Spellen", "Statistieken", "Instellingen", "Lokale back-ups en privacy", "Luisteren en problemen oplossen", "Inhoud, bronnen en licentie");

    private static HelpDocument Localized(string language, string title, string intro, params string[] headings)
    {
        var bodies = language switch
        {
            "de" => GermanBodies(),
            "fr" => FrenchBodies(),
            "es" => SpanishBodies(),
            "pt" => PortugueseBodies(),
            "nl" => DutchBodies(),
            _ => EnglishBodies(),
        };
        var ids = new[] { "start", "accessibility", "cards", "quiz", "words", "games", "statistics", "settings", "cloud", "audio", "data" };
        return new HelpDocument(title, intro, headings.Select((heading, index) => new HelpSection(ids[index], heading, bodies[index])).ToArray());
    }

    private static string[] EnglishBodies() =>
    [
            "The top bar selects the study language and level. App language is changed in Settings. The menu opens Home, Cards, Quiz, Words, Games, Statistics, Settings, Help and About. F11 and Esc control full screen.",
            "All controls have text names, visible focus, large targets and high-contrast support. Tab and Shift+Tab move between controls. Enter invokes a button; Cards use Space, 1–4, arrow keys and U; Quiz uses 1–4 and Enter.",
            "Reveal the meaning before continuing a card. Listen reads the target word with a local Windows voice. Choose Next after reading; Undo brings back the last completed card. Use the known tool in Cards or Words when you want to mark a word as known.",
            "Quiz always opens a grid of numbered test islands for the selected study language and level. Each island has 20 questions; the last may have fewer. Each separately saves its exact questions, choices, answers and position. Open its tile to resume or see completed results. Choose another test island returns to the picker without losing progress. Read the definition and choose one of four words. The answer is saved before Continue becomes available. Feedback names the correct answer and your choice. Look at the answer opens an example or comparison. First-attempt Quiz results are separate from game scores and Cards ratings. Try this test again restarts that island's whole test.",
            "Words searches by word, meaning or category and combines known and favourite filters. Previous word and Next word show one complete result at a time. Meaning, example, Listen, favourite and known tools remain available. Choose a 20-question test opens the numbered island grid for the selected study language and level. Search filters do not change the tests. Each island has 20 questions; the last may have fewer. Each saves its own exact questions, choices, answers and position. Open its tile to resume or see completed results. Returning to the picker keeps progress. Try this test again restarts that island's whole test.",
            "The native catalog contains 25 games: Hangman, Cloze Test, Dictation, Speed Round, Survival Streak, True or False, Word Class, Memory, Odd One Out, Word Race, Sentence Scramble, Reading Comprehension, Word Morph, Bingo, Boss Rush, CodyCross, Crossword, Daily Challenge, Scrabble, Word Guess, Category Sprint, Listening Choice, Matrix, Clue Detective and Scramble. Each game follows the selected study language and level.",
            "Statistics separates Overview, Answers and Cards. Unique words, Quiz attempts, Game attempts and Cards self-ratings are different measurements. Rating rows include text and counts; paging is announced to screen readers.",
            "My practice contains App language, daily goal, reduced motion and untimed practice. Colors & text controls text size and contrast-safe colour previews. For grown-ups contains local backups and confirmation-gated local reset.",
            "Learning is offline by default. Make a copy and Open a copy are explicit local backup actions; loading validates and makes a safety copy first.",
            "Listen needs an installed Windows 11 speech voice for the target language. If Listen does not work, open Windows Settings > Time & language > Language & region, add the language if needed, then open Language options and install Speech. Restart YDKE after setup. A language or level change may briefly reload local data; controls are disabled during that operation.",
            "Vocabulary and reading data are bundled locally. Some content comes from open community projects and keeps its own licence. YDKE source code and interface use the PolyForm Noncommercial License 1.0.0; see About for copyright holders, permission addresses and full links. YDKE is not an official exam provider product."
    ];

    private static string[] GermanBodies() =>
    [
        "Die obere Leiste wählt die Lernsprache und das Niveau. Die App-Sprache änderst du unter Einstellungen > Meine Übungen. Das Menü öffnet Startseite, Karten, Quiz, Wörter, Phrasal Verbs, Spiele, Statistik, Einstellungen, Hilfe und Über YDKE. Auf der Seite Phrasal Verbs ist die Niveau-Auswahl absichtlich deaktiviert; auf anderen Seiten ist sie wieder aktiv. F11 und Esc steuern den Vollbildmodus.",
        "Alle Bedienelemente haben Textnamen, sichtbaren Fokus, große Ziele und Unterstützung für hohen Kontrast. Tab und Shift+Tab bewegen den Fokus. Enter aktiviert eine Schaltfläche; Karten verwenden Leertaste, 1–4, Pfeiltasten und U, das Quiz 1–4 und Enter.",
        "Decke bei einer Karte zuerst die Bedeutung auf. Anhören verwendet eine lokale Windows-Stimme. Hilf mir, Schwer, Das wusste ich und Leicht bewerten dein Erinnern; Das wusste ich und Leicht teilen die Bekannt-Markierung mit Wörter. Rückgängig ist vor dem Verlassen möglich.",
        "Das Quiz öffnet immer ein Raster nummerierter Testinseln für die gewählte Lernsprache und das Niveau. Jede Insel hat 20 Fragen; die letzte kann weniger haben. Jede speichert ihre genauen Fragen und Auswahlmöglichkeiten sowie deine Antworten und deine Position getrennt. Öffne ihre Kachel zum Fortsetzen oder für die Ergebnisse eines abgeschlossenen Tests. Mit Wähle eine andere Testinsel kommst du ohne Fortschrittsverlust zur Auswahl zurück. Lies die Bedeutung und wähle eines von vier Wörtern. Die Antwort wird gespeichert, bevor Weiter verfügbar wird. Die Rückmeldung nennt die richtige Antwort und deine Wahl. Schau dir die Antwort an öffnet ein Beispiel oder einen Vergleich. Quiz-Ergebnisse des ersten Versuchs bleiben von Spielpunkten und Kartenbewertungen getrennt. Wiederhole diesen Test startet den ganzen Test dieser Insel neu.",
        "Wörter kann nach Wort, Bedeutung oder Kategorie suchen und bekannte sowie favorisierte Wörter filtern. Vorheriges Wort und Nächstes Wort zeigen jeweils ein vollständiges Ergebnis. Bedeutung, Beispiel, Anhören, Favorit und Bekannt bleiben erreichbar. Wähle einen Test mit 20 Fragen öffnet das nummerierte Inselraster für die gewählte Lernsprache und das Niveau. Suchfilter ändern die Tests nicht. Jede Insel hat 20 Fragen; die letzte kann weniger haben. Jede speichert ihre genauen Fragen, Auswahlmöglichkeiten, Antworten und deine Position getrennt. Öffne ihre Kachel zum Fortsetzen oder für die Ergebnisse eines abgeschlossenen Tests. Bei der Rückkehr zur Auswahl bleibt dein Fortschritt erhalten. Wiederhole diesen Test startet den ganzen Test dieser Insel neu.",
        "Der native Katalog enthält 25 Spiele: Hangman, Cloze Test, Dictation, Speed Round, Survival Streak, True or False, Word Class, Memory, Odd One Out, Word Race, Sentence Scramble, Reading Comprehension, Word Morph, Bingo, Boss Rush, CodyCross, Crossword, Daily Challenge, Scrabble, Word Guess, Category Sprint, Listening Choice, Matrix, Clue Detective und Scramble. Jedes Spiel folgt Lernsprache und Niveau.",
        "Statistik trennt Übersicht, Antworten und Karten. Einzigartige Wörter, Quizversuche, Spielversuche und Kartenbewertungen sind verschiedene Messwerte. Bewertungszeilen zeigen Text und Anzahl; Seitenwechsel werden von Screenreadern angesagt.",
        "Meine Übungen enthält App-Sprache, Tagesziel, weniger Bewegung und Spielen ohne Zeitlimit. Farben & Text steuert Schriftgröße und kontrastreiche Vorschauen. Für Erwachsene enthält lokale Sicherungen und das bestätigte Zurücksetzen lokaler Daten.",
        "Das Lernen funktioniert standardmäßig offline. Eine Kopie machen und Eine Kopie öffnen sind ausdrückliche lokale Sicherungsaktionen; beim Laden wird zuerst geprüft und eine Sicherheitskopie erstellt.",
        "Anhören benötigt eine installierte Windows-11-Sprachstimme für die Zielsprache. Wenn Anhören nicht funktioniert, öffne Windows-Einstellungen > Zeit & Sprache > Sprache & Region, füge die Sprache bei Bedarf hinzu und installiere unter Sprachoptionen die Sprachausgabe. Starte YDKE danach neu. Beim Wechsel von Sprache oder Niveau werden lokale Daten kurz neu geladen; währenddessen sind Bedienelemente deaktiviert.",
        "Wortschatz und Lesetexte sind lokal gebündelt. Einige Inhalte stammen aus offenen Community-Projekten und behalten ihre eigene Lizenz. Quellcode und Oberfläche von YDKE stehen unter der PolyForm Noncommercial License 1.0.0; Copyright und vollständige Links findest du unter Über YDKE. YDKE ist kein offizielles Produkt eines Prüfungsanbieters."
    ];

    private static string[] FrenchBodies() =>
    [
        "La barre supérieure choisit la langue d’apprentissage et le niveau. La langue de l’application se change dans Réglages > Mon entraînement. Le menu ouvre Accueil, Cartes, Quiz, Mots, Phrasal Verbs, Jeux, Statistiques, Réglages, Aide et À propos. Sur la page Phrasal Verbs, le sélecteur de niveau est volontairement désactivé ; il redevient actif sur les autres pages. F11 et Échap contrôlent le plein écran.",
        "Chaque contrôle possède un nom textuel, un focus visible, une grande zone d’action et un mode contraste élevé. Tab et Maj+Tab déplacent le focus. Entrée active un bouton ; les cartes utilisent Espace, 1–4, les flèches et U, et le quiz utilise 1–4 et Entrée.",
        "Avec une carte, affiche d’abord le sens. Écouter utilise une voix Windows locale. Aide-moi, Difficile, Je savais et Facile évaluent ton rappel ; Je savais et Facile partagent la marque connu avec Mots. Annuler mon choix est disponible avant de quitter.",
        "Le quiz s'ouvre toujours sur une grille d'îlots de test numérotés pour la langue d'apprentissage et le niveau choisis. Chaque îlot a 20 questions ; le dernier peut en avoir moins. Chacun enregistre séparément ses questions et choix exacts, tes réponses et ta position. Ouvre sa case pour reprendre ou voir les résultats s'il est terminé. Choisis un autre îlot de test revient à la grille sans perdre ta progression. Lis le sens et choisis un mot parmi quatre. La réponse est enregistrée avant que Continuer soit disponible. Le retour indique le bon mot et ton choix. Regarde la réponse ouvre un exemple ou une comparaison. Les résultats du premier essai restent séparés des scores de jeux et des auto-évaluations des cartes. Refais ce test permet de recommencer tout le test de cet îlot.",
        "Mots recherche par mot, sens ou catégorie et combine les filtres connu et favori. Mot précédent et Mot suivant affichent un résultat complet à la fois. Sens, exemple, Écouter, favori et connu restent accessibles. Choisis un test de 20 questions ouvre la grille d'îlots numérotés pour la langue d'apprentissage et le niveau choisis. Les filtres de recherche ne changent pas les tests. Chaque îlot a 20 questions ; le dernier peut en avoir moins. Chacun conserve séparément ses questions et choix exacts, tes réponses et ta position. Ouvre sa case pour reprendre ou voir les résultats s'il est terminé. Revenir à la grille conserve ta progression. Refais ce test permet de recommencer tout le test de cet îlot.",
        "Le catalogue natif contient 25 jeux : Hangman, Cloze Test, Dictation, Speed Round, Survival Streak, True or False, Word Class, Memory, Odd One Out, Word Race, Sentence Scramble, Reading Comprehension, Word Morph, Bingo, Boss Rush, CodyCross, Crossword, Daily Challenge, Scrabble, Word Guess, Category Sprint, Listening Choice, Matrix, Clue Detective et Scramble. Chaque jeu suit la langue et le niveau sélectionnés.",
        "Statistiques sépare Vue d’ensemble, Réponses et Cartes. Les mots uniques, essais de quiz, essais de jeux et évaluations de cartes sont des mesures différentes. Les lignes affichent le texte et le nombre ; la pagination est annoncée aux lecteurs d’écran.",
        "Mon entraînement contient la langue de l’application, l’objectif quotidien, moins de mouvement et jouer sans chronomètre. Couleurs & texte règle la taille et les aperçus à contraste sûr. Pour adultes contient les sauvegardes locales et la réinitialisation locale confirmée.",
        "L’apprentissage fonctionne hors ligne par défaut. Faire une copie et Ouvrir une copie sont des actions explicites de sauvegarde locale ; le chargement vérifie le fichier et crée d’abord une copie de sécurité.",
        "Écouter nécessite une voix de synthèse Windows 11 installée pour la langue cible. Si Écouter ne fonctionne pas, ouvre Paramètres Windows > Heure et langue > Langue et région, ajoute la langue si nécessaire, puis installe la composante Parole dans Options linguistiques. Redémarre YDKE après l'installation. Un changement de langue ou de niveau peut recharger les données locales ; les contrôles sont désactivés pendant cette opération.",
        "Les listes de mots et les textes sont regroupés localement. Certains contenus viennent de projets communautaires ouverts et gardent leur propre licence. Le code et l’interface YDKE utilisent la PolyForm Noncommercial License 1.0.0 ; les titulaires et les liens complets se trouvent dans À propos. YDKE n’est pas un produit officiel d’un examen."
    ];

    private static string[] SpanishBodies() =>
    [
        "La barra superior selecciona el idioma de aprendizaje y el nivel. El idioma de la aplicación se cambia en Ajustes > Mi práctica. El menú abre Inicio, Tarjetas, Prueba, Palabras, Phrasal Verbs, Juegos, Estadísticas, Ajustes, Ayuda y Acerca de. En la página Phrasal Verbs, el selector de nivel se desactiva a propósito; vuelve a estar activo en otras páginas. F11 y Esc controlan la pantalla completa.",
        "Todos los controles tienen nombres de texto, foco visible, objetivos grandes y compatibilidad con alto contraste. Tab y Mayús+Tab mueven el foco. Enter activa un botón; las tarjetas usan Espacio, 1–4, flechas y U, y la prueba usa 1–4 y Enter.",
        "En Tarjetas muestra primero el significado. Escuchar usa una voz local de Windows. Ayúdame, Difícil, Lo sabía y Fácil registran cómo recuerdas; Lo sabía y Fácil comparten la marca conocida con Palabras. Deshacer mi elección está disponible antes de salir.",
        "La prueba siempre abre una cuadrícula de islas de prueba numeradas para el idioma de aprendizaje y el nivel elegidos. Cada isla tiene 20 preguntas; la última puede tener menos. Cada una guarda por separado sus preguntas y opciones exactas, tus respuestas y tu posición. Abre su casilla para continuar o ver los resultados si está completada. Elige otra isla de prueba vuelve al selector sin perder tu progreso. Lee el significado y elige una de cuatro palabras. La respuesta se guarda antes de activar Continuar. La respuesta muestra la palabra correcta y tu elección. Mira la respuesta abre un ejemplo o una comparación. Los resultados del primer intento se mantienen separados de los puntos de juegos y las valoraciones de tarjetas. Repite esta prueba reinicia toda la prueba de esa isla.",
        "Palabras busca por palabra, significado o categoría y combina filtros de conocidas y favoritas. Palabra anterior y Palabra siguiente muestran un resultado completo cada vez. Significado, ejemplo, Escuchar, favorita y conocida siguen disponibles. Elige una prueba de 20 preguntas abre la cuadrícula de islas numeradas para el idioma de aprendizaje y el nivel elegidos. Los filtros de búsqueda no cambian las pruebas. Cada isla tiene 20 preguntas; la última puede tener menos. Cada una conserva por separado sus preguntas y opciones exactas, tus respuestas y tu posición. Abre su casilla para continuar o ver los resultados si está completada. Volver al selector conserva tu progreso. Repite esta prueba reinicia toda la prueba de esa isla.",
        "El catálogo nativo contiene 25 juegos: Hangman, Cloze Test, Dictation, Speed Round, Survival Streak, True or False, Word Class, Memory, Odd One Out, Word Race, Sentence Scramble, Reading Comprehension, Word Morph, Bingo, Boss Rush, CodyCross, Crossword, Daily Challenge, Scrabble, Word Guess, Category Sprint, Listening Choice, Matrix, Clue Detective y Scramble. Cada juego sigue el idioma y nivel elegidos.",
        "Estadísticas separa Resumen, Respuestas y Tarjetas. Las palabras únicas, los intentos de prueba, los intentos de juegos y las valoraciones de tarjetas son medidas distintas. Las filas muestran texto y cantidad; el cambio de página se anuncia a los lectores de pantalla.",
        "Mi práctica contiene idioma de la aplicación, objetivo diario, menos movimiento y jugar sin temporizador. Colores y texto controla el tamaño y las vistas previas con contraste seguro. Para adultos contiene copias locales y el restablecimiento local confirmado.",
        "El aprendizaje funciona sin conexión por defecto. Hacer una copia y Abrir una copia son acciones explícitas de copia local; al cargar se valida el archivo y se crea primero una copia de seguridad.",
        "Escuchar necesita una voz de Windows 11 instalada para el idioma de destino. Si Escuchar no funciona, abre Configuración de Windows > Hora e idioma > Idioma y región, agrega el idioma si hace falta y en Opciones de idioma instala Voz. Reinicia YDKE después de la instalación. Cambiar de idioma o nivel puede recargar los datos locales; los controles se desactivan durante la operación.",
        "Las listas y textos están incluidos localmente. Algunos contenidos proceden de proyectos comunitarios abiertos y conservan su licencia. El código y la interfaz de YDKE usan PolyForm Noncommercial License 1.0.0; los titulares y enlaces completos aparecen en Acerca de. YDKE no es un producto oficial de ningún examen."
    ];

    private static string[] PortugueseBodies() =>
    [
        "A barra superior escolhe o idioma de aprendizagem e o nível. O idioma da aplicação muda em Definições > A minha prática. O menu abre Início, Cartões, Teste, Palavras, Phrasal Verbs, Jogos, Estatísticas, Definições, Ajuda e Sobre. Na página Phrasal Verbs, o seletor de nível fica intencionalmente desativado; nas outras páginas volta a ficar ativo. F11 e Esc controlam o ecrã inteiro.",
        "Todos os controlos têm nomes de texto, foco visível, alvos grandes e suporte para alto contraste. Tab e Shift+Tab movem o foco. Enter ativa um botão; os cartões usam Espaço, 1–4, setas e U, e o teste usa 1–4 e Enter.",
        "Nos Cartões mostra primeiro o significado. Ouvir usa uma voz local do Windows. Ajuda-me, Difícil, Eu sabia e Fácil registam a tua recordação; Eu sabia e Fácil partilham a marca conhecida com Palavras. Anular a escolha está disponível antes de sair.",
        "O teste abre sempre uma grelha de ilhas de teste numeradas para o idioma de aprendizagem e o nível escolhidos. Cada ilha tem 20 perguntas; a última pode ter menos. Cada uma guarda separadamente as suas perguntas e opções exatas, as tuas respostas e a tua posição. Abre o seu bloco para continuar ou ver os resultados se estiver concluída. Escolhe outra ilha de teste volta ao seletor sem perderes o progresso. Lê o significado e escolhe uma de quatro palavras. A resposta é guardada antes de Continuar ficar disponível. O feedback identifica a resposta certa e a tua escolha. Vê a resposta abre um exemplo ou uma comparação. Os resultados da primeira tentativa ficam separados das pontuações dos jogos e das avaliações dos cartões. Repete este teste recomeça todo o teste dessa ilha.",
        "Palavras pesquisa por palavra, significado ou categoria e combina filtros de conhecidas e favoritas. Palavra anterior e Palavra seguinte mostram um resultado completo de cada vez. Significado, exemplo, Ouvir, favorita e conhecida continuam acessíveis. Escolhe um teste com 20 perguntas abre a grelha de ilhas numeradas para o idioma de aprendizagem e o nível escolhidos. Os filtros de pesquisa não alteram os testes. Cada ilha tem 20 perguntas; a última pode ter menos. Cada uma guarda separadamente as suas perguntas e opções exatas, as tuas respostas e a tua posição. Abre o seu bloco para continuar ou ver os resultados se estiver concluída. Voltar ao seletor mantém o progresso. Repete este teste recomeça todo o teste dessa ilha.",
        "O catálogo nativo contém 25 jogos: Hangman, Cloze Test, Dictation, Speed Round, Survival Streak, True or False, Word Class, Memory, Odd One Out, Word Race, Sentence Scramble, Reading Comprehension, Word Morph, Bingo, Boss Rush, CodyCross, Crossword, Daily Challenge, Scrabble, Word Guess, Category Sprint, Listening Choice, Matrix, Clue Detective e Scramble. Cada jogo segue o idioma e nível selecionados.",
        "Estatísticas separa Visão geral, Respostas e Cartões. Palavras únicas, tentativas do teste, tentativas dos jogos e avaliações dos cartões são medidas diferentes. As linhas mostram texto e quantidade; a paginação é anunciada aos leitores de ecrã.",
        "A minha prática contém idioma da aplicação, objetivo diário, menos movimento e jogar sem temporizador. Cores e texto controla o tamanho e as pré-visualizações com contraste seguro. Para adultos contém cópias locais e a reposição local confirmada.",
        "A aprendizagem funciona offline por predefinição. Fazer uma cópia e Abrir uma cópia são ações explícitas de cópia local; o carregamento valida o ficheiro e cria primeiro uma cópia de segurança.",
        "Ouvir precisa de uma voz do Windows 11 instalada para o idioma de destino. Se Ouvir não funcionar, abre Definições do Windows > Hora e idioma > Idioma e região, adiciona o idioma se for preciso e em Opções do idioma instala Fala. Reinicia o YDKE após a instalação. Mudar de idioma ou nível pode recarregar os dados locais; os controlos ficam desativados durante essa operação.",
        "As listas e os textos estão incluídos localmente. Alguns conteúdos vêm de projetos comunitários abertos e mantêm a sua licença. O código e a interface do YDKE usam a PolyForm Noncommercial License 1.0.0; os titulares e links completos estão em Sobre. O YDKE não é um produto oficial de nenhum exame."
    ];

    private static string[] DutchBodies() =>
    [
        "De bovenbalk kiest de leertaal en het niveau. De app-taal wijzig je via Instellingen > Mijn oefeningen. Het menu opent Start, Kaarten, Toets, Woorden, Phrasal Verbs, Spellen, Statistieken, Instellingen, Help en Over YDKE. Op de pagina Phrasal Verbs is de niveauselector bewust uitgeschakeld; op andere pagina's wordt die weer ingeschakeld. F11 en Esc regelen volledig scherm.",
        "Alle bedieningselementen hebben tekstnamen, zichtbare focus, grote doelen en ondersteuning voor hoog contrast. Tab en Shift+Tab verplaatsen de focus. Enter activeert een knop; Kaarten gebruikt Spatie, 1–4, pijltjestoetsen en U, en de Toets gebruikt 1–4 en Enter.",
        "Toon bij Kaarten eerst de betekenis. Luisteren gebruikt een lokale Windows-stem. Help mij, Moeilijk, Ik wist het en Makkelijk registreren hoe goed je je herinnert; Ik wist het en Makkelijk delen de bekende-markering met Woorden. Keuze ongedaan maken is beschikbaar voordat je vertrekt.",
        "De toets opent altijd een raster met genummerde testeilanden voor de gekozen leertaal en het niveau. Elk eiland heeft 20 vragen; het laatste kan er minder hebben. Elk slaat zijn exacte vragen, keuzes, antwoorden en jouw positie apart op. Open de tegel om verder te gaan of de resultaten van een voltooide test te bekijken. Kies een ander testeiland brengt je terug naar het keuzescherm zonder voortgang te verliezen. Lees de betekenis en kies een van vier woorden. Het antwoord wordt opgeslagen voordat Doorgaan beschikbaar wordt. Feedback noemt het juiste antwoord en jouw keuze. Bekijk het antwoord opent een voorbeeld of vergelijking. Eerste pogingen van de Toets blijven apart van spelpunten en kaartbeoordelingen. Met Maak deze test opnieuw begin je de hele test van dat eiland opnieuw.",
        "Woorden zoekt op woord, betekenis of categorie en combineert bekende en favoriete filters. Vorig woord en Volgend woord tonen één volledig resultaat tegelijk. Betekenis, voorbeeld, Luisteren, favoriet en bekend blijven beschikbaar. Kies een test met 20 vragen opent het raster met genummerde eilanden voor de gekozen leertaal en het niveau. Zoekfilters veranderen de tests niet. Elk eiland heeft 20 vragen; het laatste kan er minder hebben. Elk bewaart zijn exacte vragen, keuzes, antwoorden en jouw positie apart. Open de tegel om verder te gaan of de resultaten van een voltooide test te bekijken. Teruggaan naar het keuzescherm bewaart je voortgang. Met Maak deze test opnieuw begin je de hele test van dat eiland opnieuw.",
        "De native catalogus bevat 25 spellen: Hangman, Cloze Test, Dictation, Speed Round, Survival Streak, True or False, Word Class, Memory, Odd One Out, Word Race, Sentence Scramble, Reading Comprehension, Word Morph, Bingo, Boss Rush, CodyCross, Crossword, Daily Challenge, Scrabble, Word Guess, Category Sprint, Listening Choice, Matrix, Clue Detective en Scramble. Elk spel volgt de gekozen leertaal en het niveau.",
        "Statistieken scheidt Overzicht, Antwoorden en Kaarten. Unieke woorden, toets pogingen, spelpogingen en kaartbeoordelingen zijn verschillende metingen. Rijen tonen tekst en aantallen; paginawissels worden voorgelezen aan schermlezers.",
        "Mijn oefeningen bevat app-taal, dagelijks doel, minder beweging en spelen zonder timer. Kleuren en tekst regelt tekstgrootte en previews met veilig contrast. Voor volwassenen bevat lokale back-ups en een bevestigde lokale reset.",
        "Leren werkt standaard offline. Een kopie maken en Een kopie openen zijn bewuste lokale back-upacties; laden controleert het bestand en maakt eerst een veiligheidskopie.",
        "Luisteren heeft een geïnstalleerde Windows 11-stem voor de doeltaal nodig. Als Luisteren niet werkt, open Windows-instellingen > Tijd en taal > Taal en regio, voeg de taal zo nodig toe en installeer bij Taalopties Spraak. Start YDKE daarna opnieuw. Een taal- of niveauwijziging kan lokale gegevens kort opnieuw laden; bediening wordt dan uitgeschakeld.",
        "Woordlijsten en leesteksten zijn lokaal meegeleverd. Sommige inhoud komt uit open communityprojecten en behoudt de eigen licentie. De broncode en interface van YDKE gebruiken PolyForm Noncommercial License 1.0.0; houders en volledige links staan bij Over YDKE. YDKE is geen officieel examenproduct."
    ];
}
